require "jekyll"
require "jekyll-crds/version"
require "jekyll-crds/client"
require "jekyll-crds/env"
require "jekyll-crds/commands/crds"
require "jekyll-crds/generators/env-generator"
require "jekyll-crds/hooks/shared_templates"
